name: Release Resume

on:
  release:
    types: [ published ]

permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Build the LaTex resume using a GitHub Action
      - name: LaTeX Action
        uses: fudan-mse/latex-action@v0.0.1
        with:
          root_file: resume.tex

      - name: Prepare gh-pages folder
        run: |
          mkdir ../gh-pages
          mv resume.pdf ../gh-pages
          cp README.md ../gh-pages
          cp resume.tex ../gh-pages
          cp .gitignore ../gh-pages

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ../gh-pages
